# Generated by Django 5.1.4 on 2025-01-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignedTo',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
    ]
