# Generated by Django 5.1.4 on 2025-01-18 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime.today),
        ),
    ]
