# Generated by Django 5.1.4 on 2025-01-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0007_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='dueDate',
        ),
    ]
