# Generated by Django 5.1.4 on 2025-01-27 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0008_rename_due_date_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(verbose_name=datetime.datetime.today),
        ),
    ]
