# Generated by Django 5.1.4 on 2025-01-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0009_alter_task_duedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
