# Generated by Django 5.1.4 on 2025-01-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0010_rename_full_name_contact_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignedTo',
        ),
    ]
