# Generated by Django 5.1.4 on 2025-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0012_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_in_board', models.IntegerField()),
                ('todo', models.IntegerField()),
                ('in_progress', models.IntegerField()),
                ('await_feedback', models.IntegerField()),
                ('done', models.IntegerField()),
                ('prio_urgent', models.IntegerField()),
            ],
        ),
    ]
