# Generated by Django 5.1.4 on 2025-02-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0013_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='earliest_due_date',
            field=models.DateField(auto_now=True),
        ),
    ]
