# Generated by Django 5.1.3 on 2025-02-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_taskmanagement', '0017_alter_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
